language: go

go:
  - 1.14

before_install:
  - go get -t -v ./...
  - docker run -p 5984:5984 -d --name cdb -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=nimda

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
