language: go

go:
  - 1.14

before_install:
  - docker run -p 5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=nimda --name cdb -d couchdb:2.3
  - docker ps -a
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
