language: go

go:
  - 1.8

before_install:
  - docker run -p 5984:5984 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=nimda --name cdb -d couchdb:2.3
  - curl -X GET http://admin:nimda@127.0.0.1:5984/
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
